namespace SteamCommon.Models;

using System.Text.Json.Serialization;

// This has been generated by Visual Studio 2022 - This may not be "clean"

public class AppDetails
{
    [JsonPropertyName("success")] public bool Success { get; set; }

    [JsonPropertyName("data")] public AppDetailsData Data { get; set; }
}

public class AppDetailsData
{
    [JsonPropertyName("type")] public string Type { get; set; }

    [JsonPropertyName("name")] public string Name { get; set; }

    [JsonPropertyName("steam_appid")] public int SteamAppId { get; set; }

    [JsonPropertyName("required_age")] public int RequiredAge { get; set; }

    [JsonPropertyName("is_free")] public bool IsFree { get; set; }

    [JsonPropertyName("controller_support")] public string ControllerSupport { get; set; }

    [JsonPropertyName("detailed_description")] public string DetailedDescription { get; set; }

    [JsonPropertyName("about_the_game")] public string AboutTheGame { get; set; }

    [JsonPropertyName("short_description")] public string ShortDescription { get; set; }

    [JsonPropertyName("supported_languages")] public string SupportedLanguages { get; set; }

    [JsonPropertyName("header_image")] public string HeaderImage { get; set; }

    [JsonPropertyName("capsule_image")] public string CapsuleImage { get; set; }

    [JsonPropertyName("capsule_imagev5")] public string CapsuleImagev5 { get; set; }

    [JsonPropertyName("website")] public string? Website { get; set; }

    [JsonPropertyName("pc_requirements")] public PcRequirements PCRequirements { get; set; }

    // TODO: Handle this in a strongly-typed away
    [JsonPropertyName("mac_requirements")] public dynamic MacRequirements { get; set; }

    // TODO: Handle this in a strongly-type way
    [JsonPropertyName("linux_requirements")] public dynamic LinuxRequirements { get; set; }

    [JsonPropertyName("legal_notice")] public string LegalNotice { get; set; }

    [JsonPropertyName("developers")] public string[] Developers { get; set; }

    [JsonPropertyName("publishers")] public string[] Publishers { get; set; }

    [JsonPropertyName("price_overview")] public PriceOverview PriceOverview { get; set; }

    [JsonPropertyName("packages")] public int[] Packages { get; set; }

    [JsonPropertyName("package_groups")] public PackageGroups[] PackageGroups { get; set; }

    [JsonPropertyName("platforms")] public Platforms platforms { get; set; }

    [JsonPropertyName("metacritic")] public Metacritic Metacritic { get; set; }

    [JsonPropertyName("categories")] public Category[] Categories { get; set; }

    [JsonPropertyName("genres")] public Genre[] Genres { get; set; }

    [JsonPropertyName("screenshots")] public Screenshot[] Screenshots { get; set; }

    [JsonPropertyName("movies")] public Movie[] Movies { get; set; }

    [JsonPropertyName("recommendations")] public Recommendations Recommendations { get; set; }

    [JsonPropertyName("achievements")] public Achievements Achievements { get; set; }

    [JsonPropertyName("release_date")] public ReleaseDate ReleaseDate { get; set; }

    [JsonPropertyName("support_info")] public SupportInfo SupportInfo { get; set; }

    [JsonPropertyName("background")] public string Background { get; set; }

    [JsonPropertyName("background_raw")] public string BackgroundRaw { get; set; }

    [JsonPropertyName("content_descriptors")] public ContentDescriptors ContentDescriptors { get; set; }

    [JsonPropertyName("ratings")] public Dictionary<string, Ratings> Ratings { get; set; }
}

public class PcRequirements
{
    [JsonPropertyName("minimum")] public string Minimum { get; set; }

    [JsonPropertyName("recommended")] public string Recommended { get; set; }
}

public class PriceOverview
{
    [JsonPropertyName("currency")] public string Currency { get; set; }

    [JsonPropertyName("initial")] public int Initial { get; set; }

    [JsonPropertyName("final")] public int Final { get; set; }

    [JsonPropertyName("discount_percent")] public int DiscountPercent { get; set; }

    [JsonPropertyName("initial_formatted")] public string InitialFormatted { get; set; }

    [JsonPropertyName("final_formatted")] public string FinalFormatted { get; set; }
}

public class Platforms
{
    [JsonPropertyName("windows")] public bool Windows { get; set; }

    [JsonPropertyName("mac")] public bool Mac { get; set; }

    [JsonPropertyName("linux")] public bool Linux { get; set; }
}

public class Metacritic
{
    [JsonPropertyName("score")] public int Score { get; set; }

    [JsonPropertyName("url")] public string Url { get; set; }
}

public class Recommendations
{
    [JsonPropertyName("total")] public int Total { get; set; }
}

public class Achievements
{
    [JsonPropertyName("total")] public int Total { get; set; }

    [JsonPropertyName("highlighted")] public Highlighted[] Highlighted { get; set; }
}

public class Highlighted
{
    [JsonPropertyName("name")] public string Name { get; set; }

    [JsonPropertyName("path")] public string Path { get; set; }
}

public class ReleaseDate
{
    [JsonPropertyName("coming_soon")] public bool ComingSoon { get; set; }

    [JsonPropertyName("date")] public string Date { get; set; }
}

public class SupportInfo
{
    [JsonPropertyName("url")] public string Url { get; set; }

    [JsonPropertyName("email")] public string Email { get; set; }
}

public class ContentDescriptors
{
    // TODO: Handle this in a strongly-typed way
    [JsonPropertyName("ids")] public dynamic Ids { get; set; }

    // TODO: Handle this in a strongly-typed way
    [JsonPropertyName("notes")] public dynamic Notes { get; set; }
}

public class Ratings
{
    [JsonPropertyName("rating")] public string Rating { get; set; }

    [JsonPropertyName("descriptors")] public string Descriptors { get; set; }

    [JsonPropertyName("use_age_gate")] public string UseAgeGate { get; set; }

    [JsonPropertyName("required_age")] public string RequiredAge { get; set; }

    [JsonPropertyName("interactive_elements")] public string InteractiveElements { get; set; }

    [JsonPropertyName("display_online_notice")] public string DisplayOnlineNotice { get; set; }
}

public class PackageGroups
{
    [JsonPropertyName("name")] public string Name { get; set; }

    [JsonPropertyName("title")] public string Title { get; set; }

    [JsonPropertyName("description")] public string Description { get; set; }

    [JsonPropertyName("selection_text")] public string SelectionText { get; set; }

    [JsonPropertyName("save_text")] public string SaveText { get; set; }

    [JsonPropertyName("display_type")] public int DisplayType { get; set; }

    [JsonPropertyName("is_recurring_subscription")] public string IsRecurringSubscription { get; set; }

    [JsonPropertyName("subs")] public Sub[] Subs { get; set; }
}

public class Sub
{
    [JsonPropertyName("packageid")] public int PackageId { get; set; }

    [JsonPropertyName("percent_savings_text")] public string PercentSavingsText { get; set; }

    [JsonPropertyName("percent_savings")] public int PercentSavings { get; set; }

    [JsonPropertyName("option_text")] public string OptionText { get; set; }

    [JsonPropertyName("option_description")] public string OptionDescription { get; set; }

    [JsonPropertyName("can_get_free_license")] public string CanGetFreeLicense { get; set; }

    [JsonPropertyName("is_free_license")] public bool IsFreeLicense { get; set; }

    [JsonPropertyName("price_in_cents_with_discount")] public int PriceInCentsWithDiscount { get; set; }
}

public class Category
{
    [JsonPropertyName("id")] public int Id { get; set; }

    [JsonPropertyName("description")] public string Description { get; set; }
}

public class Genre
{
    [JsonPropertyName("id")] public string Id { get; set; }

    [JsonPropertyName("description")] public string Description { get; set; }
}

public class Screenshot
{
    [JsonPropertyName("id")] public int Id { get; set; }

    [JsonPropertyName("path_thumbnail")] public string PathThumbnail { get; set; }

    [JsonPropertyName("path_full")] public string PathFull { get; set; }
}

public class Movie
{
    [JsonPropertyName("id")] public int Id { get; set; }

    [JsonPropertyName("name")] public string Name { get; set; }

    [JsonPropertyName("thumbnail")] public string Thumbnail { get; set; }

    // PixelSize (IE: 480), MaxSize (max)
    [JsonPropertyName("webm")] public Dictionary<string, string> Webm { get; set; }

    [JsonPropertyName("mp4")] public Dictionary<string, string> Mp4 { get; set; }

    [JsonPropertyName("highlight")] public bool Highlight { get; set; }
}